### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by maverickNerd** [seclab-ucr/SyzDescribe#1]
Getting compilation error, can you help ?

▶ bash ./script/build.bash
[  4%] Building CXX object lib/ToolLib/CMakeFiles/ToolLib.dir/llvm_related.cpp.o
SyzDescribe/lib/ToolLib/llvm_related.cpp: In function ‘std::__cxx11::string get_real_function_type(llvm::FunctionType*)’:
SyzDescribe/lib/ToolLib/llvm_related.cpp:69:67: error: ‘class llvm::Type’ has no member named ‘getNonOpaquePointerElementType’; did you mean ‘getPointerElementType’?
     if (ret->isPointerTy() && ret->getNumContainedTypes() && ret->getNonOpaquePointerElementType()->isStructTy()) {
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                   getPointerElementType
SyzDescribe/lib/ToolLib/llvm_related.cpp:94:74: error: ‘class llvm::Type’ has no member named ‘getNonOpaquePointerElementType’; did you mean ‘getPointerElementType’?
         if (temp->isPointerTy() && temp->getNumContainedTypes() && temp->getNonOpaquePointerElementType()->isStructTy()) {
                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                          getPointerElementType
SyzDescribe/lib/ToolLib/llvm_related.cpp: In function ‘llvm::Type* get_real_type(llvm::Type*)’:
SyzDescribe/lib/ToolLib/llvm_related.cpp:140:33: error: ‘class llvm::Type’ has no member named ‘getNonOpaquePointerElementType’; did you mean ‘getPointerElementType’?
         return get_real_type(t->getNonOpaquePointerElementType());
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                 getPointerElementType
lib/ToolLib/CMakeFiles/ToolLib.dir/build.make:62: recipe for target 'lib/ToolLib/CMakeFiles/ToolLib.dir/llvm_related.cpp.o' failed
make[2]: *** [lib/ToolLib/CMakeFiles/ToolLib.dir/llvm_related.cpp.o] Error 1
CMakeFiles/Makefile2:115: recipe for target 'lib/ToolLib/CMakeFiles/ToolLib.dir/all' failed
make[1]: *** [lib/ToolLib/CMakeFiles/ToolLib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ZHYfeng** [comment]
Use LLVM/Clang 14.
This api is not available in LLVM/Clang <= 13.
