### ISSUE TITLE
Incorrect output after executing SyzDescribe

### ISSUE THREAD

**Issue by DuckRui** [seclab-ucr/SyzDescribe#2]
hi, I would like to try using SyzDescribe, but when I executing SyzDescribe, there is no output
The command I used: tools/SyzDescribe/SyzDescribe --config_json=config.json
There is no output and I see the debug.log, it shows:
![image](https://github.com/seclab-ucr/SyzDescribe/assets/41203418/07e18800-9b08-49a1-80e9-596da170881c)
Can you help me? Thanks!

**Comment by ZHYfeng** [comment]
First I want to make sure that you have the bitcode of the related kernel modules?
Second, the LLVM/Clang to get the bitcode is the default version of Ubuntu 22.04, which LLVM/Clang 14?

**Comment by ZHYfeng** [comment]
By the way, I also update the README with info about LLVM/Clang version.
